### ISSUE TITLE
Make time outs configurable.

### ISSUE THREAD

**Issue by dubgeiser** [digipolisgent/robo-digipolis-helpers#12]
Sometimes build tasks can take up quite some time.  Ideally one should investigate why and optimize the task, but there are case where this cannot be done easily, for instance when something needs to get deployed "right away".  But, there are also tasks that just take up some time, like backing up the files/ directory in projects that have a lot of files.

Seems that by making these time outs configurable (with sensible defaults, obviously) we can circumvent this on a per-project-base.

**Comment by matthijs-va** [comment]
@dubgeiser Could you please specify which timouts should be configurable?
