### ISSUE TITLE
Unzipping db backup on MacOS gives 'trailing garbage ignored' error

### ISSUE THREAD

**Issue by dubgeiser** [digipolisgent/robo-digipolis-helpers#24]
When running digipolis:sync-local on MacOS the gunzipping of the db backup fails with error 'trailing garbage ignored'
When copying over the database backup manually from the server and then gunzipping it, this does not error.

**Comment by Jelle-S** [comment]
TL;DR
"Works on my machine"



Seems to be a Mac-specific problem, the `digipolis:sync-local` command works as it should on a Linux system.

**Comment by Jelle-S** [comment]
Using [https://www.cjmweb.net/vbindiff/](VBinDiff), you can see there are indeed trailing zeroes added to the file when downloaded through phpseclib's SCP. Not sure what causes it yet.

![image](https://user-images.githubusercontent.com/1828542/45877544-8645bd80-bd9e-11e8-8de4-bccbe75fd79f.png)
==> Top: Downloaded using filezilla, bottom downloaded using phpseclib's SCP

**Comment by Jelle-S** [comment]
Seems like a known issue:
https://github.com/phpseclib/phpseclib/issues/146

**Comment by Jelle-S** [comment]
Fixed by https://github.com/digipolisgent/robo-digipolis-deploy/pull/12
