### ISSUE TITLE
Ssh command fails when creating an tar file

### ISSUE THREAD

**Issue by wesleydv** [digipolisgent/robo-digipolis-helpers#9]
[DigipolisGent\Deploy\Ssh] data@10.25.2.151:/home/data/apps/default/files$ tar -xkzf /home/data/apps/default/backups/1491296370/1491296370_2017_04_04_10_59_30.tar.gz
 [DigipolisGent\Deploy\Ssh] 
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

 [DigipolisGent\Deploy\Ssh]  Could not execute cd -P /home/data/apps/default/files && tar -xkzf /home/data/apps/default/backups/1491296370/1491296370_2017_04_04_10_59_30.tar.gz on 10.25.2.151 on port 22 in folder /home/data/apps/default/files with message: 
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
.
 
 [DigipolisGent\Deploy\Ssh]  Exit code 1 
 [error]  Could not execute cd -P /home/data/apps/default/files && tar -xkzf /home/data/apps/default/backups/1491296370/1491296370_2017_04_04_10_59_30.tar.gz on 10.25.2.151 on port 22 in folder /home/data/apps/default/files with message: 
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
.

**Comment by matthijs-va** [comment]
Hasn't occured since april 2017, please reopen if needed.
